#!/usr/bin/env python3
"""Focused offline Linux check for supervised Helm private terminals (#32).

Run only after the build owner releases the shared binaries:
  python3 helm/tests/private_terminal.py --bin-dir /absolute/path/to/target/debug

Uses real Vessel/Voyage processes, a bounded fake provider, and a synthetic outer
PTY (never a human terminal). No builds, credentials, third-party Python packages,
or live provider. Evidence stays in the printed private temporary directory.
This is not a general terminal-emulation suite or native-platform verification.
"""
import argparse
import codecs
import errno
import fcntl
import hashlib
import http.server
import json
import os
from pathlib import Path
import re
import select
import shlex
import signal
import struct
import subprocess
import sys
import tempfile
import termios
import threading
import time
import urllib.request
import uuid


TITLE = "synthetic-private-terminal"
PROMPT = "Start the synthetic terminal fixture, then check the private capture boundary."
# This child is fixture instrumentation, not a model tool for capturing private
# traffic. It records only our generated bytes and synthetic terminal geometry.
CHILD = r'''
import json, os, select, signal, termios, time, tty
from pathlib import Path
root = Path.cwd()
identity = {"pid": os.getpid(), "start": Path("/proc/self/stat").read_text().split(") ", 1)[1].split()[19]}
(root / "child-identity.json").write_text(json.dumps(identity))
tty.setraw(0)
received = bytearray()
last, size = None, None
end = time.monotonic() + 180
while time.monotonic() < end:
    mode = (root / "mode").read_text() if (root / "mode").exists() else "application"
    if mode != last:
        last = mode
        if mode == "application":
            os.write(1, b"\x1b[?1h\x1b[?2004h\x1b[?25l\x1b[2J\x1b[H\x1b[1;38;2;17;99;201mSTYLE_PROBE\x1b[0m\r\nAPPLICATION_READY")
        elif mode == "normal":
            os.write(1, b"\x1b[?1l\x1b[?2004l\x1b[?25h\x1b[2J\x1b[HNORMAL_READY\x1b[4;8H")
        elif mode == "repeat":
            # Repeat after detach to prove capture is not reopened by detachment.
            os.write(1, b"\r\nREPEATED:" + bytes(received) + b"\r\n")
    current = list(os.get_terminal_size(0))
    if current != size:
        size = current
    temp = root / "observation.tmp"
    temp.write_text(json.dumps({"input_hex": received.hex(), "size": size, "mode": last}))
    temp.replace(root / "observation.json")
    readable, _, _ = select.select([0], [], [], .03)
    if readable:
        chunk = os.read(0, 4096)
        if not chunk:
            break
        received.extend(chunk)
        os.write(1, b"\r\nECHO:" + chunk + b"\r\n")
'''


def wait_for(observe, label, timeout=30):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        value = observe()
        if value:
            return value
        time.sleep(.03)
    raise AssertionError("timed out: " + label)


class Screen:
    """Small output probe for the CSI subset emitted by Ratatui, not a VT oracle.

    Keeping cursor/style state lets assertions examine rendered cells rather than
    treating stale text in a redraw transcript as the current screen. Unsupported
    control sequences are ignored; application input is checked independently.
    """
    def __init__(self, columns=120, rows=36):
        self.columns, self.rows = columns, rows
        self.x = self.y = 0
        self.visible = True
        self.alternate = self.paste = False
        self.bold, self.foreground = False, None
        self.cells = {}
        self.pending = ""
        self.decoder = codecs.getincrementaldecoder("utf-8")("replace")

    def feed(self, data):
        self.pending += self.decoder.decode(data)
        while self.pending:
            text = self.pending
            if text.startswith("\x1b["):
                found = re.match(r"\x1b\[([0-?]*)([ -/]*)([@-~])", text)
                if not found:
                    return
                self.pending = text[found.end():]
                raw, _, command = found.groups()
                private = raw.startswith("?")
                numbers = [int(n or 0) for n in raw.lstrip("?").split(";")]
                n = numbers[0] or 1
                if private and command in "hl":
                    for mode in numbers:
                        if mode == 25:
                            self.visible = command == "h"
                        elif mode == 1049:
                            self.alternate = command == "h"
                            self.cells.clear()
                        elif mode == 2004:
                            self.paste = command == "h"
                elif command in "Hf":
                    self.y = n - 1
                    self.x = ((numbers[1] or 1) if len(numbers) > 1 else 1) - 1
                elif command == "G":
                    self.x = n - 1
                elif command == "d":
                    self.y = n - 1
                elif command in "ABCD":
                    self.x += n if command == "C" else -n if command == "D" else 0
                    self.y += n if command == "B" else -n if command == "A" else 0
                elif command == "J" and numbers[0] in (2, 3):
                    self.cells.clear()
                elif command == "K":
                    for key in list(self.cells):
                        if key[1] == self.y and (numbers[0] == 2 or
                                numbers[0] == 0 and key[0] >= self.x or
                                numbers[0] == 1 and key[0] <= self.x):
                            del self.cells[key]
                elif command == "m":
                    while numbers:
                        code = numbers.pop(0)
                        if code == 0:
                            self.bold, self.foreground = False, None
                        elif code == 1:
                            self.bold = True
                        elif code == 22:
                            self.bold = False
                        elif code == 39:
                            self.foreground = None
                        elif code == 38 and len(numbers) >= 4 and numbers[0] == 2:
                            self.foreground = tuple(numbers[1:4])
                            del numbers[:4]
                        elif code in (38, 48) and numbers and numbers[0] == 5 and len(numbers) >= 2:
                            del numbers[:2]
                        elif code == 48 and len(numbers) >= 4 and numbers[0] == 2:
                            del numbers[:4]
                continue
            if text.startswith("\x1b]"):
                found = re.search(r"\x07|\x1b\\", text)
                if not found:
                    return
                self.pending = text[found.end():]
                continue
            if text[0] == "\x1b":
                if len(text) < 2:
                    return
                self.pending = text[2:]
                continue
            char, self.pending = text[0], text[1:]
            if char == "\r":
                self.x = 0
            elif char == "\n":
                self.y += 1
            elif char == "\b":
                self.x = max(0, self.x - 1)
            elif char >= " ":
                self.cells[self.x, self.y] = (char, self.bold, self.foreground)
                self.x += 1

    def text(self):
        return "\n".join("".join(self.cells.get((x, y), (" ",))[0]
                                for x in range(self.columns)) for y in range(self.rows))

    def position(self, text):
        for y, row in enumerate(self.text().splitlines()):
            if text in row:
                return row.index(text), y
        return None


class OuterPTY:
    def __init__(self, command, env, cwd, path):
        self.master, self.slave = os.openpty()
        self.original = termios.tcgetattr(self.slave)
        self.screen = Screen()
        self.resize(120, 36)
        self.log = path.open("wb")
        # A fresh single-threaded helper acquires the controlling terminal.
        # Never use Python preexec_fn in this threaded provider fixture.
        self.process = subprocess.Popen([sys.executable, str(Path(__file__).resolve()),
            "_pty_exec", *command], stdin=self.slave, stdout=self.slave,
            stderr=self.slave, cwd=cwd, env=env, start_new_session=True)

    def resize(self, columns, rows):
        self.screen.columns, self.screen.rows = columns, rows
        fcntl.ioctl(self.slave, termios.TIOCSWINSZ, struct.pack("HHHH", rows, columns, 0, 0))
        if hasattr(self, "process"):
            self.process.send_signal(signal.SIGWINCH)

    def pump(self):
        while select.select([self.master], [], [], 0)[0]:
            try:
                chunk = os.read(self.master, 65536)
            except OSError as error:
                if error.errno == errno.EIO:
                    break
                raise
            if not chunk:
                break
            self.log.write(chunk)
            self.log.flush()
            self.screen.feed(chunk)
        return self.screen

    def send(self, data):
        assert self.process.poll() is None, "Helm exited before input"
        # Inputs are bounded below; do not silently drop a partial PTY write.
        assert os.write(self.master, data) == len(data)

    def until(self, predicate, label, timeout=30):
        def observed():
            screen = self.pump()
            assert self.process.poll() is None, "Helm exited while waiting for " + label
            return predicate(screen)
        return wait_for(observed, label, timeout)

    def exited_restored(self, success=True):
        wait_for(lambda: (self.pump(), self.process.poll() is not None)[1], "Helm exit")
        assert (self.process.returncode == 0) == success, "unexpected Helm exit status"
        assert termios.tcgetattr(self.slave) == self.original, "outer termios not restored"
        assert not self.screen.alternate, "alternate screen not restored"
        assert not self.screen.paste, "bracketed paste not restored"
        assert self.screen.visible, "outer cursor not restored"

    def close(self):
        forced = False
        if self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.process.kill()
                self.process.wait(timeout=5)
                forced = True
        self.pump()
        self.log.close()
        os.close(self.master)
        os.close(self.slave)
        assert not forced, "Helm required forced cleanup"


class Provider(http.server.BaseHTTPRequestHandler):
    def log_message(self, *_args):
        pass

    def do_POST(self):
        self.connection.settimeout(10)
        try:
            assert self.path == "/v1/chat/completions"
            size = int(self.headers["Content-Length"])
            assert 0 < size <= 4 * 1024 * 1024
            body = json.loads(self.rfile.read(size))
            assert body["stream"] is True
            self.server.requests.append(body)
            step = len(self.server.requests)
            assert [m["content"] for m in body["messages"] if m["role"] == "user"] == [PROMPT]
            assert "process" in {t["function"]["name"] for t in body["tools"]}
            if step == 1:
                arguments = {"action": "start", "name": TITLE,
                             "command": "exec python3 " + shlex.quote(str(self.server.child))}
            elif step == 2:
                assert body["messages"][-1]["role"] == "tool"
                self.server.ready.set()
                assert self.server.release.wait(150), "private journey timed out"
                assert not self.server.aborted.is_set(), "fixture aborted"
                arguments = {"action": "read", "name": TITLE}
            elif step == 3:
                result = body["messages"][-1]
                assert result["role"] == "tool" and "model capture unavailable" in result["content"]
                arguments = {"action": "write", "name": TITLE, "data": "MODEL_WRITE_MUST_NOT_ARRIVE"}
            elif step == 4:
                result = body["messages"][-1]
                assert result["role"] == "tool" and "private" in result["content"].lower()
                arguments = {"action": "terminate", "name": TITLE}
            elif step == 5:
                assert body["messages"][-1]["role"] == "tool"
                arguments = None
            else:
                raise AssertionError("unexpected provider replay")
            delta = {"content": "Synthetic terminal check finished."} if arguments is None else {
                "tool_calls": [{"index": 0, "id": "terminal-step-" + str(step), "type": "function",
                                "function": {"name": "process", "arguments": json.dumps(arguments)}}]}
            reason = "stop" if arguments is None else "tool_calls"
            payload = "".join("data: " + json.dumps({"choices": [{"index": 0, "delta": d,
                              "finish_reason": r}]}) + "\n\n" for d, r in ((delta, None), ({}, reason)))
            payload = (payload + "data: [DONE]\n\n").encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)
            self.wfile.flush()
        except Exception as error:
            self.server.errors.append(repr(error))
            self.close_connection = True


def alive(identity):
    try:
        stat = Path(f"/proc/{identity['pid']}/stat").read_text().split(") ", 1)[1].split()
        return stat[19] == identity["start"] and stat[0] != "Z"
    except FileNotFoundError:
        return False


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bin-dir", required=True, type=Path)
    args = parser.parse_args()
    if not __debug__:
        parser.error("run without -O; assertions are the test oracle")
    if sys.platform != "linux":
        parser.error("Linux-only check; other platforms are not verified")
    binaries = args.bin_dir.resolve()
    for name in ("helm", "vessel", "voyage"):
        assert (binaries / name).is_file(), "missing binary: " + name
    root = Path(tempfile.mkdtemp(prefix="hpt-"))
    print("evidence: " + str(root), flush=True)
    workspace, directory = root / "workspace", root / "vessel"
    workspace.mkdir(mode=0o700)
    child = workspace / "synthetic.py"
    child.write_text(CHILD)
    env = {"PATH": "/usr/bin:/bin", "LANG": "C.UTF-8", "TERM": "xterm-256color",
           "COLORTERM": "truecolor"}
    for key in ("HOME", "XDG_CONFIG_HOME", "XDG_STATE_HOME", "XDG_DATA_HOME", "XDG_CACHE_HOME"):
        path = root / key.lower()
        path.mkdir(mode=0o700)
        env[key] = str(path)
    session = str(uuid.uuid4())
    evidence = {"session_id": session, "checks": [], "binary_sha256": {},
                "limitations": ["Linux synthetic PTY, not a human terminal or native macOS/Windows",
                                "Local socket loss tested; no deployed remote TLS or terminal hardware check",
                                "Small outer CSI probe; not a complete VT emulator"]}
    for name in ("helm", "vessel", "voyage"):
        with (binaries / name).open("rb") as handle:
            evidence["binary_sha256"][name] = hashlib.file_digest(handle, "sha256").hexdigest()
    server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), Provider)
    server.daemon_threads = False
    server.requests, server.errors, server.child = [], [], child
    server.ready, server.release, server.aborted = (threading.Event() for _ in range(3))
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    config = root / "config.toml"
    config.write_text('provider = "openai-chat"\nmodel = "fixture-model"\napi_key_required = false\n'
                      f'base_url = "http://127.0.0.1:{server.server_port}/v1"\n'
                      'provider_retry_attempts = 1\naccess = "unrestricted"\ncontext_window = 0\n')
    config.chmod(0o600)
    supervisor, runner, clients, logs = None, None, [], []
    canary = "PRIVATE_CANARY_" + uuid.uuid4().hex

    def log(name):
        handle = (root / name).open("wb")
        logs.append(handle)
        return handle

    def request(command, allow_error=False):
        credential = json.loads((directory / "process-http.json").read_text())
        req = urllib.request.Request(credential["endpoint"] + "/v1/vessel/command",
            data=json.dumps({"protocol": 1, "command": command}).encode(),
            headers={"Authorization": "Bearer " + credential["token"], "Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=10) as response:
            payload = response.read(4 * 1024 * 1024 + 1)
        assert 0 < len(payload) <= 4 * 1024 * 1024
        result = json.loads(payload)
        assert result["protocol"] == 1
        if allow_error:
            assert result.get("error"), "expected terminal operation error"
            evidence.setdefault("terminal_errors", []).append({"error": result["error"], "outcome_unknown": result.get("outcome_unknown")})
            return result
        assert not result.get("outcome_unknown"), "unexpected uncertain operation; do not replay"
        assert result.get("error") is None, result.get("error")
        return result["result"]

    def snapshot():
        assert not server.errors, server.errors
        return request({"op": "snapshot", "session_id": session})["result"]

    def observation():
        path = workspace / "observation.json"
        return json.loads(path.read_text()) if path.exists() else {}

    def observed_bytes():
        return bytes.fromhex(observation().get("input_hex", ""))

    def connect(*arguments):
        client = OuterPTY([str(binaries / "helm"), "connect", "--directory", str(directory),
                           "--no-start", *arguments], env, workspace,
                          root / f"outer-{len(clients)}.ansi")
        clients.append(client)
        return client

    def owned_voyages():
        identities = []
        for proc in Path("/proc").iterdir():
            if not proc.name.isdigit():
                continue
            try:
                argv = (proc / "cmdline").read_bytes().split(b"\0")
                if (argv[:3] == [os.fsencode(binaries / "voyage"), b"serve", b"--directory"]
                        and len(argv) > 3 and Path(os.fsdecode(argv[3])).parent == directory / "sessions"):
                    identities.append({"pid": int(proc.name),
                        "start": (proc / "stat").read_text().split(") ", 1)[1].split()[19]})
            except (FileNotFoundError, ProcessLookupError):
                pass
        return identities

    def stop_owned(identity):
        if alive(identity):
            try:
                descriptor = os.pidfd_open(identity["pid"])
                try:
                    if alive(identity):
                        signal.pidfd_send_signal(descriptor, signal.SIGTERM)
                finally:
                    os.close(descriptor)
            except ProcessLookupError:
                pass

    try:
        vessel_log = log("vessel.log")
        supervisor = subprocess.Popen([str(binaries / "vessel"), "local-serve", "--directory",
            str(directory), "--voyage-binary", str(binaries / "voyage")], cwd=workspace, env=env,
            stdin=subprocess.DEVNULL, stdout=vessel_log, stderr=subprocess.STDOUT)
        wait_for(lambda: (directory / "process-http.json").exists(), "Vessel discovery")
        request({"op": "start_configured", "session_id": session, "command_id": str(uuid.uuid4()),
                 "workspace": str(workspace), "config_path": str(config)})
        runner = subprocess.Popen([str(binaries / "helm"), "connect", "--directory", str(directory),
            "--no-start", "run", session, PROMPT], cwd=workspace, env=env, stdin=subprocess.DEVNULL,
            stdout=log("run.out"), stderr=log("run.err"))
        wait_for(server.ready.is_set, "fake provider observes successful process.start")
        wait_for(observation, "synthetic child ready")
        initial = snapshot()
        run = initial["run"]["run_id"]
        tool_text = next(m["content"] for m in initial["messages"] if m["role"] == "tool")
        terminal = re.search(r"[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}", tool_text)
        assert terminal, "process.start did not return a terminal UUID"
        terminal = terminal.group()
        evidence.update(run_id=run, terminal_id=terminal)
        resources = initial.get("session_resources", [])
        assert any(r.get("kind") == "root_terminals" and r.get("run_id") == run for r in resources), "live PTY obligation missing"
        evidence["live_resource_obligations"] = resources
        incarnation = request({"op": "inspect", "session_id": session})["incarnation"]
        def voyage(command, allow_error=False, owner=incarnation):
            return request({**command, "session_id": session, "incarnation": owner}, allow_error)
        operation = {"op": "terminal", "run_id": run, "terminal_id": terminal, "operation": {"action": "snapshot"}}
        voyage(operation, True, owner=str(uuid.uuid4()))
        voyage({**operation, "run_id": str(uuid.uuid4())}, True)
        voyage({**operation, "terminal_id": str(uuid.uuid4())}, True)
        evidence["checks"].append("live root-terminal obligation and stale incarnation/run/terminal refusal")

        tui = connect()
        tui.until(lambda s: "F3" in s.text(), "Helm supervised voyage view")
        tui.send(b"\x1bOR")  # xterm F3: real metadata discovery, no private API shortcut.
        tui.until(lambda s: TITLE in s.text() and "Choose a program" in s.text(), "F3 discovery")
        tui.send(b"\r")
        tui.until(lambda s: "PRIVATE TERMINAL" in s.text() and "APPLICATION_READY" in s.text(),
                  "Enter opens private terminal")
        evidence["checks"].append("real helm connect F3 discovery and Enter attachment")
        tui.until(lambda s: not s.visible, "child cursor hidden")
        position = tui.screen.position("STYLE_PROBE")
        assert position and tui.screen.cells[position][1:] == (True, (17, 99, 201)), "cell style lost"
        evidence["checks"].append("bold truecolor cell and hidden cursor rendered")

        tui.send(b"\x1b[A")
        wait_for(lambda: observed_bytes() == b"\x1bOA", "application cursor input encoding")
        paste = ("paste_" + canary).encode()
        tui.send(b"\x1b[200~" + paste + b"\x1b[201~")
        expected = b"\x1bOA\x1b[200~" + paste + b"\x1b[201~"
        wait_for(lambda: observed_bytes() == expected, "application bracketed paste framing")
        tui.until(lambda s: canary in s.text(), "synthetic private echo visible only in attachment")
        evidence["checks"].append("application cursor mode, bracketed paste and synthetic private echo")
        (workspace / "mode").write_text("normal")
        tui.until(lambda s: "NORMAL_READY" in s.text() and s.visible, "normal cursor mode and visible cursor")
        row = tui.screen.position("NORMAL_READY")[1]
        assert (tui.screen.x, tui.screen.y) == (7, row + 3), "child cursor position lost"
        tui.send(b"\x1b[A")
        expected += b"\x1b[A"
        wait_for(lambda: observed_bytes() == expected, "normal cursor input encoding")
        tui.send(b"\x1b[200~plain_paste\x1b[201~")
        expected += b"plain_paste"
        wait_for(lambda: observed_bytes() == expected, "paste unwrapped when child disables mode")
        tui.resize(103, 31)
        wait_for(lambda: (tui.pump(), observation().get("size") == [103, 27])[1], "resize reaches child PTY")
        evidence["checks"].append("normal cursor, mode-aware plain paste, cursor position and resize")

        tail = b"PRIVATE_QUEUED_TAIL_MUST_BE_DISCARDED"
        tui.send(b"\x1d" + tail)  # One write: detach and queued tail never become chat input.
        tui.until(lambda s: "PRIVATE TERMINAL" not in s.text() and "F3" in s.text(), "Ctrl+] returns to Helm")
        assert observed_bytes() == expected, "detach byte or queued tail entered child"
        assert tail.decode() not in tui.screen.text(), "private tail entered the composer"
        (workspace / "mode").write_text("repeat")
        wait_for(lambda: observation().get("mode") == "repeat", "child repeats private echo after detach")
        tui.send(b"\x11")  # Ctrl+Q leaves the full-screen client without cancelling the run.
        tui.exited_restored()
        evidence["checks"].append("Ctrl+] detaches without input forwarding; TUI exit restores outer modes")

        # Measure complete private HTTP round trips (not a remote-network benchmark).
        costs = []
        for columns, rows in ((80, 24), (240, 120)):
            voyage({**operation, "operation": {"action": "resize", "columns": columns, "rows": rows}})
            start = time.monotonic_ns()
            measured = voyage(operation)
            elapsed = (time.monotonic_ns() - start) / 1_000_000
            screen_value = measured["result"]["screen"]
            assert (screen_value["columns"], screen_value["height"]) == (columns, rows)
            costs.append({"columns": columns, "rows": rows, "roundtrip_ms": elapsed,
                          "reserialized_reply_bytes": len(json.dumps(measured, separators=(",", ":"), ensure_ascii=False).encode())})
        evidence["loopback_private_screen_costs"] = costs
        evidence["checks"].append("bounded 80x24 and maximal 240x120 private snapshot round trips")
        explicit = connect("terminal", session, "--run", run, "--terminal", terminal)
        explicit.until(lambda s: "PRIVATE TERMINAL" in s.text() and canary in s.text(), "explicit CLI reattachment")
        explicit.send(b"\x1d")
        explicit.exited_restored()
        assert observed_bytes() == expected, "reattach or detach injected child input"
        evidence["checks"].append("CLI reattachment retains synthetic private screen; normal detach restores termios")
        for stop_signal in (signal.SIGTERM, signal.SIGHUP):
            interrupted = connect("terminal", session, "--run", run, "--terminal", terminal)
            interrupted.until(lambda s: "PRIVATE TERMINAL" in s.text() and canary in s.text(),
                              "attachment active before signal")
            interrupted.process.send_signal(stop_signal)
            interrupted.exited_restored()
            assert observed_bytes() == expected, "signal detach injected private input"
            assert alive(json.loads((workspace / "child-identity.json").read_text())), "detach cancelled child"
        evidence["checks"].append("SIGTERM and SIGHUP detach restore modes without cancelling child")
        # Runtime policy remains authoritative after a human attachment.
        for access in ("read-only", "unrestricted"):
            voyage({"op": "set_access", "command_id": str(uuid.uuid4()),
                    "expected_revision": snapshot()["revision"],
                    "expires_at_ms": int(time.time() * 1000) + 60_000, "access": access})
            if access == "read-only":
                voyage({**operation, "operation": {"action": "write", "bytes": list(b"POLICY_DENIED_INPUT")}}, True)
                assert observed_bytes() == expected, "read-only policy allowed private input"
        evidence["checks"].append("live read-only policy refuses private writes without replay")

        lost = connect("terminal", session, "--run", run, "--terminal", terminal)
        lost.until(lambda s: "PRIVATE TERMINAL" in s.text(), "attachment before socket loss")
        survivor = json.loads((workspace / "child-identity.json").read_text())
        supervisor.terminate()
        assert supervisor.wait(timeout=10) == 0, "supervisor shutdown failed"
        lost.exited_restored(success=False)
        assert alive(survivor), "Vessel disconnect cancelled independent Voyage PTY"
        assert observed_bytes() == expected, "socket loss replayed input"
        supervisor = subprocess.Popen([str(binaries / "vessel"), "local-serve", "--directory",
            str(directory), "--voyage-binary", str(binaries / "voyage")], cwd=workspace, env=env,
            stdin=subprocess.DEVNULL, stdout=log("vessel-restart.log"), stderr=subprocess.STDOUT)
        def reconnected():
            try:
                return request({"op": "inspect", "session_id": session}).get("incarnation") == incarnation
            except (OSError, ValueError, AssertionError):
                return False
        wait_for(reconnected, "same independent owner after Vessel restart")
        assert observed_bytes() == expected, "supervisor restart replayed input"
        evidence["checks"].append("socket loss restores CLI and does not cancel/replay; restarted Vessel observes same owner")

        # A partially decoded paste cannot be reset through Crossterm's public API.
        # With no consumed detach chord, child exit must stop the TUI, not resume chat.
        abnormal = connect()
        abnormal.until(lambda s: "F3" in s.text(), "second TUI ready")
        abnormal.send(b"\x1bOR")
        abnormal.until(lambda s: TITLE in s.text() and "Choose a program" in s.text(), "second F3 inventory")
        abnormal.send(b"\r")
        abnormal.until(lambda s: "PRIVATE TERMINAL" in s.text(), "abnormal-handoff attachment")
        abnormal.send(b"\x1b[200~INCOMPLETE_PRIVATE_" + canary.encode())
        server.release.set()
        abnormal.exited_restored(success=False)
        evidence["checks"].append("child exit with incomplete private paste stops TUI and restores outer modes")
        completed = wait_for(lambda: (s if (s := snapshot()).get("run", {}).get("state") == "completed"
                                     and s.get("pending_cleanup_run") is None else None), "run completion")
        # Its socket was deliberately stopped above; the follower must report loss,
        # not claim that the independent accepted run was cancelled or replay it.
        assert runner.wait(timeout=10) != 0, "run follower hid the injected socket loss"
        evidence["run_follower_exit_after_injected_loss"] = runner.returncode
        assert completed.get("session_resources") == [], "root-terminal obligation not released"
        assert completed.get("cleanup", {}).get("phase") == "observed", "cleanup not positively observed"
        assert completed.get("cleanup", {}).get("pending") == [], "cleanup tasks still pending"
        evidence["observed_cleanup"] = completed["cleanup"]
        assert len(server.requests) == 5, "unexpected provider replay"
        assert canary not in json.dumps(server.requests), "private canary reached provider"
        assert canary not in json.dumps(completed), "private canary reached canonical snapshot"
        assert observed_bytes() == expected, "model input reached private child"
        assert any("model capture unavailable" in m.get("content", "") for m in completed["messages"]
                   if m["role"] == "tool"), "missing model privacy-gap evidence"
        # Search only this fixture's state and diagnostics, never actual user data.
        for tree in (directory, root / "xdg_data_home", root / "xdg_state_home"):
            for path in tree.rglob("*"):
                if path.is_file():
                    assert canary.encode() not in path.read_bytes(), "canary persisted in runtime state"
        for handle in logs:
            handle.flush()
            assert canary.encode() not in Path(handle.name).read_bytes(), "canary reached runtime diagnostics"
        (root / "completed.json").write_text(json.dumps(completed, indent=2))
        evidence["checks"].append("private output withheld after detach; model write refused; no canary in provider/history/state/logs")
        identity = json.loads((workspace / "child-identity.json").read_text())
        wait_for(lambda: not alive(identity), "process.terminate reaps synthetic child")
        wait_for(lambda: not owned_voyages(), "completed voyage suspension")
    finally:
        server.aborted.set()
        server.release.set()
        cleanup_errors = []
        for client in clients:
            try:
                client.close()
            except Exception as error:
                cleanup_errors.append(str(error))
        if runner is not None and runner.poll() is None:
            runner.terminate()
            try:
                runner.wait(timeout=5)
            except subprocess.TimeoutExpired:
                runner.kill()
                runner.wait(timeout=5)
                cleanup_errors.append("run frontend required forced cleanup")
        try:
            for identity in owned_voyages():
                stop_owned(identity)
            wait_for(lambda: not owned_voyages(), "fixture voyage cleanup", timeout=15)
            identity_path = workspace / "child-identity.json"
            if identity_path.exists():
                identity = json.loads(identity_path.read_text())
                stop_owned(identity)
                wait_for(lambda: not alive(identity), "fixture child cleanup", timeout=10)
        except Exception as error:
            cleanup_errors.append(str(error))
        if supervisor is not None:
            supervisor.terminate()
            try:
                supervisor.wait(timeout=10)
            except subprocess.TimeoutExpired:
                supervisor.kill()
                supervisor.wait(timeout=5)
                cleanup_errors.append("Vessel required forced cleanup")
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)
        for handle in logs:
            handle.close()
        evidence["cleanup_errors"] = cleanup_errors
        evidence["remaining_voyages"] = owned_voyages()
        evidence["provider_stopped"] = not thread.is_alive()
        (root / "provider-requests.json").write_text(json.dumps(server.requests, indent=2))
        (root / "provider-errors.json").write_text(json.dumps(server.errors, indent=2))
        (root / "lifecycle.json").write_text(json.dumps(evidence, indent=2))
        assert not cleanup_errors, cleanup_errors
        assert not thread.is_alive(), "provider thread did not stop"
    assert not server.errors, server.errors
    print("PASS: " + "; ".join(evidence["checks"]))


if __name__ == "__main__":
    if len(sys.argv) > 2 and sys.argv[1] == "_pty_exec":
        fcntl.ioctl(0, termios.TIOCSCTTY, 0)
        os.execve(sys.argv[2], sys.argv[2:], os.environ)
    main()
