import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import {gunzipSync} from 'node:zlib';
import {randomUUID} from 'node:crypto';
import {Worker} from '../worker.mjs';
import {publicAddress} from '../security.mjs';
const executable=process.env.CHROMIUM||'/usr/bin/chromium';
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));

test('address classification',()=>{
 for(const ip of ['127.0.0.1','::1','::ffff:127.0.0.1','10.1.2.3','169.254.169.254','100.64.0.1','192.168.1.1','192.0.0.1','192.0.2.1','192.88.99.1','198.18.0.1','198.19.255.254','198.51.100.1','203.0.113.1','2001::1','2001:01ff::1','2001:0db8::1','2002:0808:0808::1','3fff::1'])assert.equal(publicAddress(ip),false);
 for(const ip of ['8.8.8.8','192.0.43.8','192.0.3.1','192.0.255.254','2001:500:88:200::8','2001:0200::1','2606:4700:4700::1111'])assert.equal(publicAddress(ip),true);
});

test('replay resources use host-captured bytes and never retain stylesheet URLs',()=>{
 const worker=new Worker();
 worker.assets.set('https://site.example/static/logo.png','data:image/png;base64,AA==');
 const events=[{type:2,data:{node:{type:0,childNodes:[{type:2,tagName:'link',attributes:{href:'https://site.example/static/site.css',_cssText:'body{background:url(logo.png)}'},childNodes:[]},{type:2,tagName:'img',attributes:{src:'https://unknown.example/track.png'},childNodes:[]},{type:2,tagName:'meta',attributes:{'http-equiv':'refresh',content:'0;url=https://unknown.example/'},childNodes:[]},{type:2,tagName:'iframe',attributes:{srcdoc:'<script>location="https://unknown.example"</script>'},childNodes:[]}]}}}];
 worker.inlineAssets(events,'https://site.example/page');
 const [stylesheet,image]=events[0].data.node.childNodes;
 assert.equal(stylesheet.attributes.href,undefined);
 assert.match(stylesheet.attributes._cssText,/data:image\/png;base64,AA==/);
 assert.equal(image.attributes.src,'');
 assert.equal(events[0].data.node.childNodes[2].attributes.content,undefined);
 assert.equal(events[0].data.node.childNodes[3].attributes.srcdoc,undefined);
});

test('one sandboxed browser serves bounded live DOM to authorized viewers',{timeout:90000},async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'worker333-'));
 const worker=new Worker(),sockets=new Set();
 const server=http.createServer((req,res)=>{
  if(req.url==='/blocked')return;
  res.setHeader('Content-Type','text/html');
  res.end(`<body style="background:#159;color:white"><h1>Synthetic worker</h1><input aria-label="entry"><button onclick="document.querySelector('h1').textContent='clicked'">Click</button><button onclick="alert('synthetic dialog')">Dialog</button><canvas width="320" height="160" onclick="document.querySelector('h1').textContent='surface'"></canvas></body>`);
 });
 server.on('connection',socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const origin=`http://127.0.0.1:${server.address().port}`;
 t.after(async()=>{await worker.dispose();for(const socket of sockets)socket.destroy();await new Promise(resolve=>server.close(resolve));await fs.rm(root,{recursive:true,force:true});});
 const request=(op,args={})=>worker.request({id:randomUUID(),op,browser:worker.browser,epochs:{...worker.epochs},...args});
 const call=async(op,args={})=>{const response=await request(op,args);assert.equal(response.ok,true,JSON.stringify(response));return response.result;};
 const events=result=>JSON.parse(gunzipSync(Buffer.from(result.value.data_base64,'base64')).toString());
 await call('init',{config:{root,executable,public_web:true,origins:[{origin,private_network:true}],width:640,height:480}});
 await call('open');await call('agent',{action:{kind:'navigate',url:origin}});
 const sandbox=await worker.task.newPage();await sandbox.goto('chrome://sandbox');
 assert.match(await sandbox.locator('body').innerText(),/Seccomp-BPF sandbox\s+Yes/);await sandbox.close();
 const viewer=randomUUID(),other=randomUUID();await call('join',{viewer});await call('join',{viewer:other});
 const first=await call('mirror',{viewer,since:0});
 assert.equal(first.value.reset,true);assert.match(JSON.stringify(events(first)),/Synthetic worker/);
 assert.ok(events(first).every(event=>event&&Number.isInteger(event.type)));
 assert.ok(events(first).some(event=>event.type===4));
 assert.ok(events(first).some(event=>event.type===2));
 assert.equal(first.value.visuals?.length,1,'visible canvas receives a localized image');
 assert.ok(first.value.visuals[0].id>0&&first.value.visuals[0].data_base64.length>0);
 assert.equal(worker.task.contexts().length,1,'the task browser has one context and no encoder browser');
 const second=await call('mirror',{viewer:other,since:0});assert.match(JSON.stringify(events(second)),/Synthetic worker/);
 const blocked=request('agent',{action:{kind:'navigate',url:origin+'/blocked'}});await sleep(200);
 const started=Date.now();await call('control',{viewer,mode:'private'});assert.ok(Date.now()-started<3000);
 assert.equal((await blocked).error.code,'control_fenced');assert.deepEqual(worker.status().viewers,[viewer]);
 assert.equal((await request('mirror',{viewer:other,since:0})).error.code,'viewer_missing');
 assert.equal((await request('agent',{action:{kind:'inspect'}})).error.code,'agent_fenced');
 const privateView=await call('mirror',{viewer,since:0});assert.equal(privateView.value.reset,true);
 const buttonId=await worker.page.evaluate(()=>globalThis.__voyageMirror.id(document.querySelector('button')));
 await call('input',{viewer,seq:1,action:{kind:'element',action:'click',node_id:buttonId,button:'left'}});
 assert.equal(await worker.page.locator('h1').innerText(),'clicked');
 const changed=await call('mirror',{viewer,since:privateView.value.cursor});assert.match(JSON.stringify(events(changed)),/clicked/);
 const canvasId=await worker.page.evaluate(()=>globalThis.__voyageMirror.id(document.querySelector('canvas')));
 await call('input',{viewer,seq:2,action:{kind:'element',action:'surface_click',node_id:canvasId,x:5000,y:5000,button:'left'}});
 assert.equal(await worker.page.locator('h1').innerText(),'surface');
 await call('input',{viewer,seq:3,action:{kind:'resize',width:400,height:600}});
 assert.deepEqual(worker.status().viewport,{width:400,height:600});
 const requestId=randomUUID();const input={id:requestId,op:'input',browser:worker.browser,epochs:{...worker.epochs},viewer,seq:4,action:{kind:'text',text:'PRIVATE-SENTINEL'}};
 assert.equal((await worker.request(input)).ok,true);assert.equal((await worker.request(input)).result.content_withheld,true);
 assert.equal((await worker.request({...input,seq:5})).error.code,'id_conflict');
 await call('disconnect',{viewer});assert.equal(worker.mode,'private');assert.equal(worker.controller,viewer);
 await call('join',{viewer});await call('control',{viewer,mode:'agent'});
 const receipts=await fs.readdir(path.join(root,'receipts'));
 for(const file of receipts)assert.doesNotMatch(await fs.readFile(path.join(root,'receipts',file),'utf8'),/PRIVATE-SENTINEL/);
 await call('close');assert.equal(worker.task,null);
});
